name: "Sphinx Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies and velotest
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    - name: Build docs
      run: |
        cd docs
        make html SPHINXOPTS="-W --keep-going"
