name: "Sphinx Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies and velotest
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    - name: Build docs
      run: |
        cd docs
        make html SPHINXOPTS="-W --keep-going"
