name: "Sphinx Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    - uses: ammaraskar/sphinx-action@7.4.7
      with:
        docs-folder: "docs/"
        build-command: 'make html SPHINXOPTS="-W --keep-going -n"'
